apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
  namespace: test-lr
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "0.1"
        memory: "64Mi"
      limits:
        cpu: "3"
        memory: "2Gi"