apiVersion: v1
kind: Pod
metadata:
  name: valid-pod
  namespace: test-lr
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "0.4"
        memory: "350Mi"
      limits:
        cpu: "0.7"
        memory: "450Mi"