apiVersion: v1
kind: Pod
metadata:
  name: test-pod-below-min
  namespace: test-lr
spec:
  containers:
  - name: test-container
    image: nginx
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"